#ifndef FS_LAYOUT_H
#define FS_LAYOUT_H

#define BLOCK_SIZE 4096

#define SUPERBLOCK_NUM 0
#define INODE_BITMAP_BLOCK_NUM 1
#define FREE_BITMAP_BLOCK_NUM 2

#define INODE_TABLE_FIRST_BLOCK 3
#define INODE_TABLE_BLOCK_COUNT 4

#define INITIAL_RESERVED_BLOCKS_MASK 0x7F

#define DIRECTORY_ENTRY_SIZE 32
#define DIRECTORY_ENTRY_INODE_SIZE 2
#define DIRECTORY_ENTRY_NAME_OFFSET DIRECTORY_ENTRY_INODE_SIZE
#define DIRECTORY_ENTRY_DOT_OFFSET 0
#define DIRECTORY_ENTRY_DOTDOT_OFFSET DIRECTORY_ENTRY_SIZE
#define DIRECTORY_ENTRY_DOTDOT_NAME_OFFSET \
    (DIRECTORY_ENTRY_DOTDOT_OFFSET + DIRECTORY_ENTRY_NAME_OFFSET)

#define DIRECTORY_FLAGS 2
#define DIRECTORY_INITIAL_SIZE (2 * DIRECTORY_ENTRY_SIZE)

#define ROOT_INODE_NUM 0

#endif